version: 2

models:
  - name: fct_menu_profit
    description: >
      事實表，呈現每個菜單品項的售價、成本與利潤資訊（粒度：每個 menu_item）。
      可用於分析不同品牌、商品類型的獲利能力。
    meta:
      owner: data@yourorg.com
      domain: menu
      sla: daily

    # 強烈建議啟用 data contracts：結構/型別一變就能在 CI 擋掉
    config:
      contracts:
        enforced: true

    columns:
      - name: menu_item_id
        description: 菜單項目的唯一識別碼
        data_type: number
        tests:
          - not_null : {}
          - unique : {}

      - name: menu_item_name
        description: 菜單項目的名稱
        data_type: string
        tests:
          - not_null : {}

      - name: truck_brand_name
        description: 所屬餐車品牌
        data_type: string
        tests:
          - not_null : {}

      - name: sale_price_usd
        description: 商品售價（美元）
        data_type: number
        tests:
          - not_null : {}
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
              severity: warn    # 允許 0 價但會警告（可改為 error）

      - name: cost_of_goods_usd
        description: 商品成本（美元）
        data_type: number
        tests:
          - not_null : {}
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
              severity: error   # 成本為負通常是錯：直接擋下

      - name: profit_usd
        description: 商品利潤（售價 - 成本）
        data_type: number
        tests:
          - not_null : {}
          # 若你確定不允許虧損，可開啟以下測試；否則改用 singular 規則分品牌檢查
          # - dbt_utils.accepted_range:
          #     min_value: 0
          #     inclusive: true
