version: 2

models:
  - name: fct_menu_profit
    description: >
      事實表，呈現每個菜單品項的售價、成本與利潤資訊（粒度：每個 menu_item）。
      可用於分析不同品牌、商品類型的獲利能力。
    meta:
      owner: data@yourorg.com
      domain: menu
      sla: daily
      grain: "one row per menu_item_id"   # 可讀性 ↑（非必填）

    config:
      contracts:
        enforced: true
      # 可選：也可在 .sql 用 config()
      # tags: ["mart","fact"]

    columns:
      - name: menu_item_id
        description: 菜單項目的唯一識別碼
        data_type: number
        tests:
          - not_null: {}        # ← 修正：冒號前後不要多空格
          - unique: {}

      - name: menu_item_name
        description: 菜單項目的名稱
        data_type: string
        tests:
          - not_null: {}

      - name: truck_brand_name
        description: 所屬餐車品牌
        data_type: string
        tests:
          - not_null: {}

      - name: sale_price_usd
        description: 商品售價（美元）
        data_type: number
        tests:
          - not_null: {}
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
              config:            # ← 建議把 severity 放進 config 區塊
                severity: warn

      - name: cost_of_goods_usd
        description: 商品成本（美元）
        data_type: number
        tests:
          - not_null: {}
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
              config:
                severity: error   # 成本為負：直接擋

      - name: profit_usd
        description: 商品利潤（售價 - 成本）
        data_type: number
        tests:
          - not_null: {}
          # 若確定不
