version: 2

sources:
  - name: SNOWFLAKE_LEARNING_DB
    schema: ALEX_LOAD_SAMPLE_DATA_FROM_S3
    tables:
      - name: MENU

models:
  - name: stg_menu
    description: "Cleaned staging table for menu items"
    columns:
      - name: menu_item_id
        tests:
          - not_null
          - unique
      - name: truck_brand_name
        tests:
          - not_null
